//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDC_TREEVIEW                    0
#define ID_TIME                         0
#define IDC_REPORTVIEW                  1
#define IDS_SELECTITEM                  1
#define ID_DLG_NONAME                   1
#define IDC_LABEL                       2
#define IDS_BUILD_MAP                   2
#define IDC_TOOLBAR                     3
#define IDS_BUILD_BATCH                 3
#define IDC_STATUSBAR                   4
#define IDS_BUILD_STARTHL               4
#define IDS_HEADER_NAME                 5
#define IDS_HEADER_DESCRIPTION          6
#define IDS_HEADER_ITEM                 7
#define IDS_HEADER_VALUE                8
#define IDS_ITEM_NAME                   9
#define IDS_ITEM_CALL                   10
#define IDS_ITEM_DESCRIPTION            11
#define IDS_ITEM_VALUE                  12
#define IDS_ITEM_TYPE                   13
#define IDS_INFO_TOOLCOUNT              14
#define IDS_INFO_COMMANDCOUNT           15
#define IDS_INFO_GAMECMDCOUNT           16
#define IDS_INFO_NAME                   17
#define IDS_INFO_DESCRIPTION            18
#define IDS_INFO_CMDCOUNT               19
#define IDS_INFO_RUN                    20
#define IDS_INFO_CALL                   21
#define IDS_INFO_VALUE                  22
#define IDS_EDIT_NEW                    23
#define IDS_EDIT_EDIT                   24
#define IDS_EDIT_DEL                    25
#define IDS_DLG_NONAME                  26
#define IDS_DLG_NOSELECT                27
#define ID_NONEWDLG                     28
#define IDS_INFO_GAME                   29
#define IDS_INFO_GAME_DIR               30
#define IDS_INFO_MAP                    31
#define IDS_CONFIRM                     32
#define IDS_NOGROUPSAVE                 33
#define IDS_NOTOOLSAVE                  34
#define IDS_NOCOMMANDSAVE               35
#define IDS_NOTOOLLOAD                  36
#define IDS_NOCOMMANDLOAD               37
#define IDS_NOGROUPSEL                  38
#define IDS_BATCHCREATED                39
#define IDS_INFO_TYPE                   40
#define IDS_QUIT                        41
#define IDS_QUIT_SAVE                   42
#define IDS_SAVED                       43
#define NEW_TYPE_GR                     50
#define NEW_TYPE_TL                     51
#define NEW_TYPE_CMD                    52
#define IDR_MENU                        101
#define IDI_WRENCH                      102
#define IDB_TOOLBAR                     103
#define IDB_NODES                       105
#define IDD_COMMAND                     106
#define IDD_TOOL                        107
#define IDD_GROUP                       108
#define IDD_NEW                         109
#define IDD_NEWNAME                     110
#define IDD_DIRECTORY                   111
#define IDD_ABOUT                       112
#define IDC_EDIT_VALUE                  1002
#define IDC_RADIO_TEXT                  1003
#define IDC_RADIO_INT                   1004
#define IDC_RADIO_BOOL                  1005
#define IDC_EDIT_CALL                   1006
#define IDC_STATIC_TYPE                 1007
#define IDC_STATIC_NAME                 1008
#define IDC_STATIC_DESCRIPTION          1009
#define IDC_STATIC_VALUE                1011
#define IDC_STATIC_CALL                 1012
#define IDC_CHECK_RUN                   1013
#define IDC_EDIT_NAME                   1014
#define IDC_EDIT_DESCRIPTION            1015
#define IDC_EDIT_MAP                    1016
#define IDC_STATIC_MAP                  1017
#define IDC_EDIT_BASEDIR                1020
#define IDC_STATIC_BASEDIR              1021
#define IDC_BUTTON_BASEDIR              1023
#define IDC_EDIT_GAMENAME               1024
#define IDC_STATIC_GAMENAME             1025
#define IDC_EDIT_GAMEDIR                1026
#define IDC_STATIC_GAMEDIR              1027
#define IDC_BUTTON_GAMEDIR              1028
#define IDC_BUTTON_MAP                  1029
#define IDC_CHECK_RUNGAME               1030
#define IDC_COMBO1                      1031
#define IDC_COMBO_TYPE                  1031
#define IDC_EDIT_WADDRIVE               1031
#define IDC_COMBO_DRIVE                 1031
#define IDC_LIST_TYPE                   1032
#define IDC_STATIC_WADDRIVE             1032
#define IDC_LIST_DIR                    1036
#define IDS_PATHTOFILL                  1037
#define IDM_BUILD_MAP                   40001
#define IDM_BUILD_BATCH                 40002
#define IDM_BESTAND_AFSLUITEN           40004
#define IDM_FILE_EXIT                   40004
#define IDM_BUILD_STARTHL               40005
#define IDM_BUILD_STARTGAME             40005
#define IDM_EDIT_NEW                    40006
#define IDM_EDIT_EDIT                   40007
#define IDM_EDIT_DEL                    40008
#define IDM_FILE_SAVE                   40009
#define IDM_FILE_LOAD                   40010
#define IDM_FILE_IMPORT_DEFHL           40013
#define IDM_FILE_IMPORT_GROUP           40014
#define IDM_FILE_IMPORT_TOOL            40015
#define IDM_FILE_IMPORT_COMMAND         40016
#define IDM_FILE_EXPORT_GROUP           40017
#define IDM_FILE_EXPORT_TOOL            40018
#define IDM_FILE_EXPORT_COMMAND         40019
#define IDM_FILE_CLOSE                  40020
#define IDM_HELP_ABOUT                  40021
#define IDM_HELP_INDEX                  40022

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         40023
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
